CREATE TABLE IF NOT EXISTS Reviews(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Review VARCHAR (255) ,
    Date DATETIME,
    Likes INT(255) NOT NULL,
    Comments INT(255) NOT NULL,
    UserID INT ,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ,
    PRIMARY KEY (ID)
)